ekyna_user_address_list:
    path: ""
    defaults:
        _controller: EkynaUserBundle:Address:list
    methods: [GET]
    options:
        _cms:
            name: "Mes adresses"
            parent: ekyna_user_account_home
            seo:
                follow: false
                index: false

ekyna_user_address_new:
    path: /new
    defaults:
        _controller: EkynaUserBundle:Address:new
    methods: [GET|POST]
    options:
        _cms:
            name: "Ajouter une adresse"
            parent: ekyna_user_address_list
            seo:
                follow: false
                index: false

ekyna_user_address_edit:
    path: /{addressId}/edit
    defaults:
        _controller: EkynaUserBundle:Address:edit
    methods: [GET|POST]
    options:
        _cms:
            name: "Modifier une adresse"
            parent: ekyna_user_address_list
            seo:
                follow: false
                index: false

ekyna_user_address_remove:
    path: /{addressId}/remove
    defaults:
        _controller: EkynaUserBundle:Address:remove
    methods: [GET|POST]
    options:
        _cms:
            name: "Supprimer une adresse"
            parent: ekyna_user_address_list
            seo:
                follow: false
                index: false
