ekyna_user_address_list:
    pattern: /
    defaults:
        _controller: EkynaUserBundle:Address:list
        _cms:
            name: "Mes adresses"
            parent: ekyna_user_account_home
    requirements:
        _method: GET

ekyna_user_address_new:
    pattern: /new
    defaults:
        _controller: EkynaUserBundle:Address:new
        _cms:
            name: "Ajouter une adresse"
            parent: ekyna_user_address_list
    requirements:
        _method: GET|POST

ekyna_user_address_edit:
    pattern: /{addressId}/edit
    defaults:
        _controller: EkynaUserBundle:Address:edit
        _cms:
            name: "Modifier une adresse"
            parent: ekyna_user_address_list
    requirements:
        _method: GET|POST

ekyna_user_address_remove:
    pattern: /{addressId}/remove
    defaults:
        _controller: EkynaUserBundle:Address:remove
        _cms:
            name: "Supprimer une adresse"
            parent: ekyna_user_address_list
    requirements:
        _method: GET|POST
