fos_user_profile_show:
    path: ""
    controller: fos_user.profile.controller:showAction
    methods: GET
    options:
        _cms:
            name: "Mon profil"
            parent: ekyna_user_account_index
            seo:
                follow: false
                index: false

fos_user_profile_edit:
    path: /edit
    controller: fos_user.profile.controller:editAction
    methods: GET|POST
    options:
        _cms:
            name: "Modifiez vos informations"
            parent: fos_user_profile_show
            seo:
                follow: false
                index: false
