fos_user_profile_show:
    path: ""
    defaults:
        _controller: FOSUserBundle:Profile:show
    methods: [GET]
    options:
        _cms:
            name: "Mon profil"
            parent: ekyna_user_account_home
            seo:
                follow: false
                index: false

fos_user_profile_edit:
    path: /edit
    defaults:
        _controller: FOSUserBundle:Profile:edit
    methods: [GET|POST]
    options:
        _cms:
            name: "Modifiez vos informations"
            parent: fos_user_profile_show
            seo:
                follow: false
                index: false
