fos_user_registration_register:
    path: ""
    controller: fos_user.registration.controller:registerAction
    methods: GET|POST
    options:
        _cms:
            name: "Créer un compte client"
            parent: ekyna_user_account_index
            seo:
                follow: false
                index: false

fos_user_registration_check_email:
    path: /check-email
    controller: fos_user.registration.controller:checkEmailAction
    methods: GET
    options:
        _cms:
            name: "Consultez votre boite mail"
            parent: fos_user_registration_register
            seo:
                follow: false
                index: false

fos_user_registration_confirm:
    path: /confirm/{token}
    controller: fos_user.registration.controller:confirmAction
    methods: GET

fos_user_registration_confirmed:
    path: /confirmed
    controller: fos_user.registration.controller:confirmedAction
    methods: GET
    options:
        _cms:
            name: "Confirmation"
            parent: fos_user_registration_register
            seo:
                follow: false
                index: false
