fos_user_registration_register:
    pattern: ""
    defaults:
        _controller: FOSUserBundle:Registration:register
        _cms:
            name: "Créer un compte client"
            parent: ekyna_user_account_home
    requirements:
        _method: GET|POST

fos_user_registration_check_email:
    pattern: /check-email
    defaults:
        _controller: FOSUserBundle:Registration:checkEmail
        _cms:
            name: "Consultez votre boite mail"
            parent: fos_user_registration_register
    requirements:
        _method: GET

fos_user_registration_confirm:
    pattern: /confirm/{token}
    defaults:
        _controller: FOSUserBundle:Registration:confirm
    requirements:
        _method: GET

fos_user_registration_confirmed:
    pattern: /confirmed
    defaults:
        _controller: FOSUserBundle:Registration:confirmed
        _cms:
            name: "Confirmation"
            parent: fos_user_registration_register
    requirements:
        _method: GET
