fos_user_resetting_request:
    pattern: /
    defaults:
        _controller: FOSUserBundle:Resetting:request
        _cms:
            name: "Réinitialisez votre mot de passe"
            parent: ekyna_user_account_home
    requirements:
        _method: GET

fos_user_resetting_send_email:
    pattern: /send-email
    defaults:
        _controller: FOSUserBundle:Resetting:sendEmail
    requirements:
        _method: POST

fos_user_resetting_check_email:
    pattern: /check-email
    defaults:
        _controller: FOSUserBundle:Resetting:checkEmail
        _cms:
            name: "Consultez votre boite mail"
            parent: fos_user_resetting_request
    requirements:
        _method: GET

fos_user_resetting_reset:
    pattern: /reset/{token}
    defaults:
        _controller: FOSUserBundle:Resetting:reset
        _cms:
            name: "Changez votre mot de passe"
            parent: fos_user_resetting_request
    requirements:
        _method: GET|POST
