fos_user_resetting_request:
    path: ""
    defaults:
        _controller: FOSUserBundle:Resetting:request
    methods: [GET]
    options:
        _cms:
            name: "Réinitialisez votre mot de passe"
            parent: ekyna_user_account_index
            seo:
                follow: false
                index: false

fos_user_resetting_send_email:
    path: /send-email
    defaults:
        _controller: FOSUserBundle:Resetting:sendEmail
    methods: [POST]

fos_user_resetting_check_email:
    path: /check-email
    defaults:
        _controller: FOSUserBundle:Resetting:checkEmail
    methods: [GET]
    options:
        _cms:
            name: "Consultez votre boite mail"
            parent: fos_user_resetting_request
            seo:
                follow: false
                index: false

fos_user_resetting_reset:
    path: /reset/{token}
    defaults:
        _controller: FOSUserBundle:Resetting:reset
    methods: [GET|POST]
    requirements:
        token: "[a-zA-Z0-9-_]+"
    options:
        _cms:
            name: "Changez votre mot de passe"
            parent: fos_user_resetting_request
            seo:
                follow: false
                index: false
