fos_user_security_login:
    path: /login
    defaults:
        _controller: EkynaUserBundle:Security:login
    methods: [GET]
    options:
        _cms:
            name: "Connexion"
            parent: ekyna_user_account_index
            seo:
                follow: false
                index: false

fos_user_security_check:
    path: /login-check
    defaults:
        _controller: FOSUserBundle:Security:check
    methods: [POST]

fos_user_security_logout:
    path: /logout
    defaults:
        _controller: FOSUserBundle:Security:logout
