fos_user_security_login:
    path: /login
    controller: EkynaUserBundle:Security:login
    methods: GET
    options:
        expose: true
        _cms:
            name: "Connexion"
            parent: ekyna_user_account_index
            seo:
                follow: false
                index: false

fos_user_security_check:
    path: /login-check
    controller: fos_user.security.controller:checkAction
    methods: POST

fos_user_security_logout:
    path: /logout
    controller: fos_user.security.controller:logoutAction
