ekyna_user_admin:
    resource: "routing/admin.yml"
    prefix:   /admin/user

hwi_oauth_redirect:
    resource: "routing/oauth.yml"
    prefix:   /oauth

ekyna_user_account:
    resource: .
    type: account
