ekyna_user_group_admin_home:
    path: /groups/
    defaults: { _controller: "ekyna_user.group.controller:homeAction" }
    requirements:
        _method: GET

ekyna_user_group_admin_list:
    path: /groups/list
    defaults: { _controller: "ekyna_user.group.controller:listAction" }
    requirements:
        _method: GET|POST

ekyna_user_group_admin_new:
    path: /groups/new
    defaults: { _controller: "ekyna_user.group.controller:newAction" }
    requirements:
        _method: GET|POST

ekyna_user_group_admin_show:
    path: /groups/{groupId}/show
    defaults: { _controller: "ekyna_user.group.controller:showAction" }
    requirements:
        _method: GET
        groupId:  \d+

ekyna_user_group_admin_edit:
    path: /groups/{groupId}/edit
    defaults: { _controller: "ekyna_user.group.controller:editAction" }
    requirements:
        _method: GET|POST
        groupId:  \d+

ekyna_user_group_admin_remove:
    path: /groups/{groupId}/remove
    defaults: { _controller: "ekyna_user.group.controller:removeAction" }
    requirements:
        _method: GET|POST
        groupId:  \d+

ekyna_user_group_admin_edit_permissions:
    path: /groups/{groupId}/edit-permissions
    defaults: { _controller: "ekyna_user.group.controller:editPermissionsAction" }
    requirements:
        _method: GET|POST
        groupId:  \d+
