ekyna_group_admin_home:
    path: /
    defaults: { _controller: "ekyna_group.controller:homeAction" }
    requirements:
        _method: GET

ekyna_group_admin_list:
    path: /list
    defaults: { _controller: "ekyna_group.controller:listAction" }
    requirements:
        _method: GET|POST

ekyna_group_admin_new:
    path: /new
    defaults: { _controller: "ekyna_group.controller:newAction" }
    requirements:
        _method: GET|POST

ekyna_group_admin_show:
    path: /{groupId}/show
    defaults: { _controller: "ekyna_group.controller:showAction" }
    requirements:
        _method: GET
        groupId:  \d+

ekyna_group_admin_edit:
    path: /{groupId}/edit
    defaults: { _controller: "ekyna_group.controller:editAction" }
    requirements:
        _method: GET|POST
        groupId:  \d+

ekyna_group_admin_remove:
    path: /{groupId}/remove
    defaults: { _controller: "ekyna_group.controller:removeAction" }
    requirements:
        _method: GET|POST
        groupId:  \d+

ekyna_group_admin_edit_permissions:
    path: /{groupId}/edit-permissions
    defaults: { _controller: "ekyna_group.controller:editPermissionsAction" }
    requirements:
        _method: GET|POST
        groupId:  \d+
