ekyna_user_user_admin_home:
    path: ""
    defaults: { _controller: "ekyna_user.user.controller:homeAction" }
    methods: [GET]

ekyna_user_user_admin_list:
    path: /list
    defaults: { _controller: "ekyna_user.user.controller:listAction" }
    methods: [GET|POST]

ekyna_user_user_admin_new:
    path: /new
    defaults: { _controller: "ekyna_user.user.controller:newAction" }
    methods: [GET|POST]

ekyna_user_user_admin_show:
    path: /{userId}/show
    defaults: { _controller: "ekyna_user.user.controller:showAction" }
    methods: [GET]
    requirements:
        userId: \d+

ekyna_user_user_admin_edit:
    path: /{userId}/edit
    defaults: { _controller: "ekyna_user.user.controller:editAction" }
    methods: [GET|POST]
    requirements:
        userId: \d+

ekyna_user_user_admin_generate_password:
    path: /{userId}/generate-password
    defaults: { _controller: "ekyna_user.user.controller:generatePasswordAction" }
    methods: [GET|POST]
    requirements:
        userId: \d+

ekyna_user_user_admin_clear_password_request:
    path: /{userId}/clear-password-request
    defaults: { _controller: "ekyna_user.user.controller:clearPasswordRequestAction" }
    methods: [GET|POST]
    requirements:
        userId: \d+

ekyna_user_user_admin_use_session:
    path: /{userId}/use-session
    defaults: { _controller: "ekyna_user.user.controller:useSessionAction" }
    methods: [GET]
    requirements:
        userId: \d+

ekyna_user_user_admin_toggle:
    path: /{userId}/toggle/{field}
    defaults: { _controller: "ekyna_user.user.controller:toggleAction", field: locked }
    methods: [GET]
    requirements:
        userId: \d+
        field: \w+

ekyna_user_user_admin_remove:
    path: /{userId}/remove
    defaults: { _controller: "ekyna_user.user.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        userId: \d+

ekyna_user_user_admin_search:
    path: /search
    defaults: { _controller: "ekyna_user.user.controller:searchAction" }
    methods: [GET]
    options:
        expose: true

ekyna_user_user_admin_find:
    path: /find
    defaults: { _controller: "ekyna_user.user.controller:findAction" }
    methods: [GET]
    options:
        expose: true