ekyna_user_admin_home:
    path: /
    defaults: { _controller: "ekyna_user.controller:homeAction" }
    requirements:
        _method: GET

ekyna_user_admin_list:
    path: /list
    defaults: { _controller: "ekyna_user.controller:listAction" }
    requirements:
        _method: GET|POST

ekyna_user_admin_new:
    path: /new
    defaults: { _controller: "ekyna_user.controller:newAction" }
    requirements:
        _method: GET|POST

ekyna_user_admin_show:
    path: /{userId}/show
    defaults: { _controller: "ekyna_user.controller:showAction" }
    requirements:
        _method: GET
        userId:  \d+

ekyna_user_admin_edit:
    path: /{userId}/edit
    defaults: { _controller: "ekyna_user.controller:editAction" }
    requirements:
        _method: GET|POST
        userId:  \d+

ekyna_user_admin_remove:
    path: /{userId}/remove
    defaults: { _controller: "ekyna_user.controller:removeAction" }
    requirements:
        _method: GET|POST
        userId:  \d+
