ekyna_user_user_admin_home:
    path: /users/
    defaults: { _controller: "ekyna_user.user.controller:homeAction" }
    requirements:
        _method: GET

ekyna_user_user_admin_list:
    path: /users/list
    defaults: { _controller: "ekyna_user.user.controller:listAction" }
    requirements:
        _method: GET|POST

ekyna_user_user_admin_new:
    path: /users/new
    defaults: { _controller: "ekyna_user.user.controller:newAction" }
    requirements:
        _method: GET|POST

ekyna_user_user_admin_show:
    path: /users/{userId}/show
    defaults: { _controller: "ekyna_user.user.controller:showAction" }
    requirements:
        _method: GET
        userId:  \d+

ekyna_user_user_admin_edit:
    path: /users/{userId}/edit
    defaults: { _controller: "ekyna_user.user.controller:editAction" }
    requirements:
        _method: GET|POST
        userId:  \d+

ekyna_user_user_admin_remove:
    path: /users/{userId}/remove
    defaults: { _controller: "ekyna_user.user.controller:removeAction" }
    requirements:
        _method: GET|POST
        userId:  \d+

ekyna_user_user_admin_search:
    path: /users/search
    defaults: { _controller: "ekyna_user.user.controller:searchAction" }
    requirements:
        _method: GET
    options:
        expose: true

ekyna_user_user_admin_find:
    path: /users/find
    defaults: { _controller: "ekyna_user.user.controller:findAction" }
    requirements:
        _method: GET
    options:
        expose: true