Ekyna\Bundle\UserBundle\Entity\User:
    attributes:
        username:
            groups: [Default, Search]
        email:
            groups: [Default, Search]
        firstName:
            groups: [Default, Search]
        lastName:
            groups: [Default, Search]
