fos_elastica:
    indexes:
        ekyna_user_user:
            types:
                doc:
                    serializer: { groups: [Search] }
                    properties:
                        email: { type: text, fields: { analyzed: { type: text, analyzer: email, search_analyzer: search } } }
                        first_name: { type: text, fields: { analyzed: { type: text, analyzer: edge, search_analyzer: search } } }
                        last_name: { type: text, fields: { analyzed: { type: text, analyzer: edge, search_analyzer: search } } }
                        group: {type: long}
                    persistence:
                        driver: orm
                        model: "%ekyna_user.user.class%"
                        provider: { batch_size: 25 }
                        listener: ~
                        finder: ~
                        repository: "%ekyna_user.user.search_repository.class%"
