fos_elastica:
    indexes:
        search:
            types:
                ekyna_user_user:
                    serializer:
                        groups: [Search]
                    mappings:
                        email: {type: string, search_analyzer: search, index_analyzer: index}
                        username: {type: string, search_analyzer: search, index_analyzer: index}
                        group: {type: long}
                    persistence:
                        driver: orm
                        model: "%ekyna_user.user.class%"
                        provider:
                            batch_size: 25
                        listener: ~
                        finder: ~
                        repository: "%ekyna_user.user.search_repository.class%"
