fos_elastica:
    indexes:
        search:
            types:
                ekyna_user_user:
                    _all: {enabled: false}
                    mappings:
                        first_name:  {search_analyzer: fr_search, index_analyzer: fr_index}
                        last_name:   {search_analyzer: fr_search, index_analyzer: fr_index}
                        email:      {search_analyzer: fr_search, index_analyzer: fr_index}
                    persistence:
                        driver: orm
                        model: %ekyna_user.user.class%
                        provider:
                            batch_size: 25
                        listener: ~
                        finder: ~
                        repository: Ekyna\Bundle\UserBundle\Search\UserRepository
