fos_user:
    db_driver: orm
    firewall_name: user
    user_class: "%ekyna_user.user.class%"
    use_flash_notifications: false
    use_username_form_type: false
    group:
        group_class: "%ekyna_user.group.class%"
    service:
        mailer: ekyna_user.mailer.default
        user_manager: ekyna_user.user_manager.default
    registration:
        form:
            type: Ekyna\Bundle\UserBundle\Form\Type\RegistrationType
        confirmation:
            template: '@FOSUser/Registration/email.html.twig'
    resetting:
        email:
            template: '@FOSUser/Resetting/email.html.twig'
