Ekyna\Bundle\UserBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [Search, Default]
        username:
            expose: true
        firstName:
            expose: true
            serialized_name: first_name
        lastName:
            expose: true
            serialized_name: last_name
        email:
            expose: true
    virtual_properties:
        __toString:
            expose: true
            serialized_name: text
            type: string
            groups: [Search]
