Ekyna\Bundle\UserBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        firstname:
            expose: true
        lastname:
            expose: true
    virtual_properties:
        getSearchText:
            expose: true
            serialized_name: text
            type: string
            groups: [Search]
