ekyna_user_account_home:
    pattern: ""
    defaults:
        _controller: EkynaUserBundle:Account:home
    requirements:
        _method: GET
    options:
        _cms:
            name: Espace client
            menus: [footer]
            position: 99
            seo:
                follow: false
                index: false

fos_user_security:
    resource: "account/security.yml"

fos_user_change_password:
    pattern: /change-password
    defaults:
        _controller: FOSUserBundle:ChangePassword:changePassword
    requirements:
        _method: GET|POST
    options:
        _cms:
            name: "Modifiez votre mot de passe"
            parent: fos_user_profile_show
            seo:
                follow: false
                index: false
