ekyna_user_account_redirect:
    path: ""
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: ekyna_user_account_index
        permanent: true

ekyna_user_account_index:
    path: /dashboard
    defaults:
        _controller: EkynaUserBundle:Account:index
    methods: [GET]
    options:
        _cms:
            name: Espace client
            menus: [footer]
            position: 99
            seo:
                follow: false
                index: false

ekyna_user_account_widget:
    path: /widget
    defaults:
        _controller: EkynaUserBundle:Account:widget
    methods: [GET]

fos_user_security:
    resource: "account/security.yml"

fos_user_change_password:
    path: /change-password
    defaults:
        _controller: FOSUserBundle:ChangePassword:changePassword
    methods: [GET|POST]
    options:
        _cms:
            name: "Modifiez votre mot de passe"
            parent: ekyna_user_account_index
            seo:
                follow: false
                index: false
