ekyna_user_account_home:
    pattern: /
    defaults:
        _controller: EkynaUserBundle:Account:home
        _cms:
            name: Espace client
            footer: true
            position: 99
            seo:
                follow: false
                index: false
    requirements:
        _method: GET

fos_user_security:
    resource: "account/security.yml"

fos_user_register:
    resource: "account/registration.yml"
    prefix: /register

fos_user_resetting:
    resource: "account/resetting.yml"
    prefix: /resetting

fos_user_profile:
    resource: "account/profile.yml"
    prefix: /profile
