ekyna_user_group_admin:
    resource: "admin/group.yml"
    prefix:   /groups

ekyna_user_user_admin:
    resource: "admin/user.yml"
    prefix:   /users

ekyna_user_address_admin:
    resource: "admin/address.yml"
    prefix:   /users/{userId}/addresses
