fos_user_profile_show:
    pattern: /
    defaults:
        _controller: FOSUserBundle:Profile:show
        _cms:
            name: "Mon profil"
            parent: ekyna_user_account_home
            menu: false
    requirements:
        _method: GET

fos_user_profile_edit:
    pattern: /edit
    defaults:
        _controller: FOSUserBundle:Profile:edit
        _cms:
            name: "Modifiez vos informations"
            parent: fos_user_profile_show
            menu: false
    requirements:
        _method: GET|POST

fos_user_change_password:
    pattern: /change-password
    defaults:
        _controller: FOSUserBundle:ChangePassword:changePassword
        _cms:
            name: "Modifiez votre mot de passe"
            parent: fos_user_profile_show
            menu: false
    requirements:
        _method: GET|POST
